### ISSUE TITLE
python version？

### ISSUE THREAD

**Issue by MrLinNing** [silvandeleemput/memcnn#10]
My pytorch version is 0.4 and python version is 3.6.6, but I found this bug,
`cd memcnn/memcnn `
`python train.py` 
```
Traceback (most recent call last):                                                                                                                                                                                    
  File "train.py", line 6, in <module>                                                                                                                                                                                 
    from memcnn.config import Config                                                                                                                                                                                             
ModuleNotFoundError: No module named 'memcnn'    
```

**Comment by MrLinNing** [comment]
I want to use pip install the lib,  and could you give me a `requirements.txt ` file?

**Comment by silvandeleemput** [comment]
Hi, judging from your error, it appears you have not included the location of the cloned repository to your Python path. 

There is currently no requirments.txt, but all the requirements can be found here in the Dockerfile:

https://github.com/silvandeleemput/memcnn/blob/7dccf480753dab34f5a60c4017c1aa5b20f9c3b5/docker/Dockerfile#L57-L71

**Comment by MrLinNing** [comment]
Did you compare your method with the original method of GPU memory consumption during training ?

**Comment by MrLinNing** [comment]
Hi， I don‘t understand why recompute the y1 and y2  in ReversibleBlockFunctio class of  revop.py ? @silvandeleemput  

```
        # Compute outputs building a sub-graph
        z1 = x1_stop + F_x2
        y2_ = x2_stop + G_z1
        y1_ = z1
```
And in backward, the y1 and y2 already exist,
```
        x, output = ctx.saved_variables #[0]
        y1, y2 = Variable.chunk(output, 2, dim=1)
        y1, y2 = y1.contiguous(), y2.contiguous()
```

**Comment by silvandeleemput** [comment]
Hi,

I have added the GPU memory consumption statistics to the results section in the [README.md](https://github.com/silvandeleemput/memcnn).
It makes quite a difference since memory requirements are O(1) for the reversible block, but O(n) otherwise, with n number of layers.

Recomputing y1 and y2 is required on the backward pass, by defining a subgraph over which to compute the gradients for the specific reversible block, since the intermediate featuremaps have all been removed during the forward pass, which results in the memory saving.

I hope this answers your questions.

**Comment by MrLinNing** [comment]
Does  "the intermediate featuremaps" here refer to the intermediate featuremaps of Fm and Gm ?
But I just found x1 and x2 are deleted  in forward process, and there is no code to delete the intermediate featuremaps of  Fm or Gm. 
```
        with set_grad_enabled(False):
            # partition in two equally sized set of channels
            x1, x2 = torch.chunk(x, 2, dim=1)
            x1, x2 = x1.contiguous(), x2.contiguous()

            # compute outputs
            with warnings.catch_warnings():
                x2var = Variable(x2, requires_grad=False, volatile=True)
            fmr = Fm.forward(x2var).data

            y1 = x1 + fmr
            x1.set_()
            del x1                 ######          free the memory for x1
            with warnings.catch_warnings():
                y1var = Variable(y1, requires_grad=False, volatile=True)
            gmr = Gm.forward(y1var).data
            y2 = x2 + gmr
            x2.set_()
            del x2               ###### free the memory for x2
            output = torch.cat([y1, y2], dim=1)
            y1.set_()
            y2.set_()
            del y1, y2
```

**Comment by silvandeleemput** [comment]
Yes, the intermediate featuremaps refer to the featuremaps of Fm and Gm.
There is no need to explicitly destroy these, since they are implicitly removed by detaching the output and input nodes within the forward method of the ReversibleBlockFunctions. Hence, the intermediate memory is freed when new memory is requested.

**Comment by MrLinNing** [comment]
@silvandeleemput  Thank you very much for your answer! In addition, I want to know whether a ReversibleBlock needs to save the corresponding output, and the next cascading ReversibleBlock also needs to save the corresponding output. In the class ReversibleBlockFunction of revop.py, you have this code,
```
        # save the (empty) input and (non-empty) output variables
        ctx.save_for_backward(x, output)
```

**Comment by silvandeleemput** [comment]
Hi, this is a little misleading, since the torch.autograd.Function requires to store the input and output graph nodes as a reference for the backward pass, but the actual data of the input node is actually freed after the forward pass in the ReversibleBlock by:

https://github.com/silvandeleemput/memcnn/blob/f83311d6bc5d0518d370062b2de63cca0a4a0899/memcnn/models/revop.py#L65-L67

**Comment by silvandeleemput** [comment]
Hi, yes this stacked memory use can generally be avoided by deleting unused pytorch tensors / models and calls to flushing the cuda cache when switching training and validation. In code it would look like this:
```python
del model
torch.cuda.empty_cache()
```
