### ISSUE TITLE
JOSS Review : Code analysis tools

### ISSUE THREAD

**Issue by sepandhaghighi** [silvandeleemput/memcnn#20]
Analyze your code by some proper tools, these tools helps to identify vulnerability and bugs in source code.

Recommended analyzers :

1. [Codacy](https://www.codacy.com/)
2. [Codefactor](https://www.codefactor.io/)
3. [LGTM](https://lgtm.com/)
4. [Codebeat](https://codebeat.co/)

also take a look at Github Marketplace.

**Comment by silvandeleemput** [comment]
For this issue, I have configured the repository for automatic code quality analysis by Codacy.
I have also added the code quality Codacy badge to the readme.rst.

Some remarks here:
* bandit's asserts security vulnerabilities were disabled since I use those a lot for pytests and none of them were actually security concerns.
* paper.md was excluded since it has a lot of minor formatting issues because of the integration with LaTeX.

@sepandhaghighi Would this be sufficient for closing this issue?

**Comment by sepandhaghighi** [comment]
> For this issue, I have configured the repository for automatic code quality analysis by Codacy.
> I have also added the code quality Codacy badge to the readme.rst.
> 
> Some remarks here:
> 
> * bandit's asserts security vulnerabilities were disabled since I use those a lot for pytests and none of them were actually security concerns.
> * paper.md was excluded since it has a lot of minor formatting issues because of the integration with LaTeX.
> 
> @sepandhaghighi Would this be sufficient for closing this issue?

Yeah, sufficient for this point.
