### ISSUE TITLE
Memory demand not constant in network depth

### ISSUE THREAD

**Issue by cetmann** [silvandeleemput/memcnn#41]
* MemCNN version: 1.3.0
* Python version: 3.6
* Operating System: Ubuntu 16

### Description

I created a very simple 3D reversible network. The memory demand does not, however, seem to be constant in the network depth, i.e.for large `n_modules` (like `20`, as in this example), Pytorch runs out of memory when calling `loss.backward()`. 

The memory demand for the weights should be negligible for this architecture.

### What I Did

```
import torch
import torch.nn as nn
import memcnn
from memcnn.models import revop

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

class ForwardOp(nn.Module):
    def __init__(self, shape):
        super(ForwardOp, self).__init__()
        self.seq = nn.Sequential(
            nn.Conv3d(in_channels=shape[1], out_channels=shape[1],
                      kernel_size=(3, 3, 3), padding=1, stride=1),
            nn.ReLU(inplace=True))

    def forward(self, x):
        return self.seq(x)


# Artificial data, cost: 1GB of memory
X = torch.rand(1, 16, 256, 256, 256).to(device)
X.requires_grad = True

# define the network by chaining together 20 additive coupling layers
n_modules = 20
layers_list = []
for i in range(n_modules):

    invertible_module = revop.AdditiveCoupling(
        Fm=ForwardOp(shape = [1, 8, 256, 256, 256]),
        Gm=ForwardOp(shape = [1, 8, 256, 256, 256])
    )

    invertible_module_wrapper = memcnn.InvertibleModuleWrapper(
        fn=invertible_module,
        keep_input=False,
        keep_input_inverse=False)
    layers_list.append(invertible_module_wrapper)

full_network = nn.Sequential(*layers_list)
full_network.to(device)
full_network.train(True)

# calculate gradients
Y = full_network.forward(X)
loss = torch.mean(Y)
loss.backward()
```

(Edit: The above code had a faulty import, which I fixed)

**Comment by silvandeleemput** [comment]
@cetmann Hi, thank you for your interest in MemCNN. I think your assertion that the memory demand (for the activations (but you know this already)) is not constant in network depth is incorrect. Instead, it appears that you are using too large inputs. Try for example to make smaller images for `X` and see what happens if you vary `n`. E.g.:
```X = torch.rand(1, 16, 1, 128, 128).to(device)```
Now try the same with `keep_input=True` for the `InvertibleModuleWrapper`.

Note, that the `AdditiveCoupling` uses internally quite a lot (approximately 4 times the input size) of memory to compute its output before it can be disposed of by the `InvertibleModuleWrapper`. It is easy to forget that you have to take that into account when picking the input sizes.

Also, I did find a small issue with the `InvertibleCheckpointFunction` that would result in unnecessary memory spikes on the GPU (this causes crashes when the memory spikes hit the GPU VRAM limit), because of the input reference not being freed in the backward pass. I am rolling out a hotfix for this issue, that should help with fitting large volumes in memory. So look out for MemCNN 1.3.1

Good luck with your project!

**Comment by cetmann** [comment]
Dear @silvandeleemput , now it works perfectly, thanks for the speedy fix! Before, a lower value of `n_modules` (i.e. a lower number of invertible layers) did not run into out-of-memory-issues, whereas a higher number did.
The input size is actually quite interesting for some 3D medical imaging applications.
