### ISSUE TITLE
Custom split dimension

### ISSUE THREAD

**Issue by ClashLuke** [silvandeleemput/memcnn#49]
### Description

It'd be great to be able to split at dimensions other than 1, enabling the usage of other layers. Currently MemCNN would split the 1st dimension, which is the batch or sequence dimension in case of RNNs, at all times.

**Comment by silvandeleemput** [comment]
@ClashLuke this would indeed be a useful feature. It should be relatively easy to add to the AdditiveCoupling and AffineCoupling classes by adding a `split_dim` attribute. I also only want to add it to default implementations (-1) since the rest are deprecated and will be removed in the future. I'll try to implement this feature soon.

TODO

* [ ] Adding attribute `split_dim` to AdditiveCoupling and AffineCoupling classes with default 1
* [ ] Add tests for splitting on other dimensions than 1
